m8ball = []
m8ball.append("Don't count on it")
m8ball.append('My reply is no')
m8ball.append('It is certain')
m8ball.append('Outlook not so good')
m8ball.append('Most likely')
m8ball.append('Concentrate and ask again')
m8ball.append('Yes definitely')
m8ball.append('Without a doubt')
m8ball.append('It is decidedly so')
m8ball.append('My sources say no')
m8ball.append('Signs point to yes')
m8ball.append('Reply hazy try again')
m8ball.append('Better not tell you now')
m8ball.append('Very doubtful')
m8ball.append('Cannot predict now')
m8ball.append('You may rely on it')
m8ball.append('Ask again later')
m8ball.append('As I see it, yes')
m8ball.append('Yes')
m8ball.append('Outlook good')